services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      network: host
    container_name: laravel_backend
    restart: unless-stopped
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:your-app-key-here
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:80"
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      network: host
    container_name: angular_frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
    ports:
      - "4200:80"
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
